export const ERROR = 'ERROR';

export const ACTIONS_FETCH_REQUEST = 'ACTIONS_FETCH_REQUEST';
export const ACTIONS_FETCH_SUCCESS = 'ACTIONS_FETCH_SUCCESS';
export const ACTIONS_FETCH_FAILURE = 'ACTIONS_FETCH_FAILURE';

export const ACTION_FETCH_REQUEST = 'ACTION_FETCH_REQUEST';
export const ACTION_FETCH_SUCCESS = 'ACTION_FETCH_SUCCESS';
export const ACTION_FETCH_FAILURE = 'ACTION_FETCH_FAILURE';

export const ACTION_ADD_REQUEST = 'ACTION_ADD_REQUEST';
export const ACTION_ADD_SUCCESS = 'ACTION_ADD_SUCCESS';
export const ACTION_ADD_FAILURE = 'ACTION_ADD_FAILURE';

export const ACTION_UPDATE_REQUEST = 'ACTION_UPDATE_REQUEST';
export const ACTION_UPDATE_SUCCESS = 'ACTION_UPDATE_SUCCESS';
export const ACTION_UPDATE_FAILURE = 'ACTION_UPDATE_FAILURE';

export const ACTION_DELETE_REQUEST = 'ACTION_DELETE_REQUEST';
export const ACTION_DELETE_SUCCESS = 'ACTION_DELETE_SUCCESS';
export const ACTION_DELETE_FAILURE = 'ACTION_DELETE_FAILURE';

export const PROJECTS_FETCH_REQUEST = 'PROJECTS_FETCH_REQUEST';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_FAILURE = 'PROJECTS_FETCH_FAILURE';

export const PROJECT_FETCH_REQUEST = 'PROJECT_FETCH_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS';
export const PROJECT_FETCH_FAILURE = 'PROJECT_FETCH_FAILURE';

export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAILURE = 'PROJECT_ADD_FAILURE';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

export const PROJECT_FETCH_ACTIONS_REQUEST = 'PROJECTS_FETCH_ACTIONS_REQUEST';
export const PROJECT_FETCH_ACTIONS_SUCCESS = 'PROJECTS_FETCH_ACTIONS_SUCCESS';
export const PROJECT_FETCH_ACTIONS_FAILURE = 'PROJECTS_FETCH_ACTIONS_FAILURE';
